# Debian-specific package configuration for LinuxInstaller
# Based on Debian installer best practices

debian:
  # Standard Mode - Full desktop setup
  standard:
    native:
      - android-tools
      - bat
      - bleachbit
      - btop
      - chromium
      - cmatrix
      - cpupower
      - dosfstools
      - duf
      - expac
      - firefox
      - fwupd
      - gnome-disk-utility
      - hwinfo
      - inxi
      - mpv
      - ncdu
      - net-tools
      - nmap
      - noto-fonts-extra
      - samba
      - sl
      - speedtest-cli
      - sshfs
      - ttf-hack-nerd
      - ttf-liberation
      - unrar
      - wakeonlan
      - xdg-desktop-portal-gtk
      - flatpak

    flatpak:
      - com.spotify.Client
      - com.dropbox.Client
      - org.filezillaproject.Filezilla
      - org.kde.kdenlive
      - org.onlyoffice.desktopeditors
      - com.github.RustRDP.RustDesk

    kde:
      install:
        - plasma-desktop
        - plasma-workspace
        - kde-plasma-applets
        - kdeconnect
        - dolphin
        - konsole
        - kate
        - okular
        - spectacle
        - ark
        - gwenview
        - kcalc
        - ksystemlog
        - kde-gtk-config
        - breeze-gtk
        - kvantum-qt5
        - kvantum-theme-breeze
        - qt5ct
        - qt6ct
        - plasma-nm
        - plasma-pa
        - xdg-desktop-portal-kde
        - discover
        - plasma-systemmonitor
        - plasma-workspace-wallpapers
        - plasma-thunderbolt
        - plasma-vault
        - plasma-sdk
